---

name: Deploy GitHub Page
run-name: Deploy GitHub Page
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          pnpm install --save-dev
          pnpm run build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy
        uses: actions/deploy-pages@v4
