# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

---

name: Deploy GitHub Page

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Reference: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Reference: https://github.com/pnpm/action-setup
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm run clean
          pnpm run build

      # Reference: https://github.com/actions/upload-pages-artifact
      - name: Archive artifact
        run: tar -cvf "$RUNNER_TEMP/artifact.tar" -C docs/dist .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error

  deploy:  # Reference: https://github.com/actions/deploy-pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
